### ISSUE TITLE
Nombre incontrôler

### ISSUE THREAD

**Issue by ValentinGratz** [snuk0/vinted-views-generator#1]
Bonjour,

J'ai tester le script et j'ai demander 10 vue dans threads, il me fait bien les 10 demandés, mais ensuite, il continue au moins jusque 30 voir 50 alors que je l'ai pas demander.
Est-ce normal ?

**Comment by simonsruggi** [comment]
The bot makes infinite requests with multithreaded tasks. 
So if you put 10 Threads, it will make 10 threads with infinite requests simultaneously.
